swagger: '2.0'

info:
  version: "0.0.1"
  title: Smash API
  description: API for http://smash.cologne

paths:
  /players:
    get:
      description: |
        Gets `Player` objects.
        Optional query param of **size** determines
        size of returned array
      parameters:
        -
          name: size
          in: query
          description: Size of array
          type: number
          format: double
      responses:
        200:
          description: Successful response
          schema:
            title: ArrayOfPlayers
            type: array
            items:
              $ref: '#/definitions/Player'

  /players/{id}:
    get:
      description: |
        Gets a specific `Player` object identified by its id
      parameters:
        - name: id
          in: path
          type: string
          description: ID of the player
          required: true
      responses:
        200:
          description: Succesful response
          schema:
            $ref: '#/definitions/Player'

definitions:
  Player:
    type: object
    properties:
      id:
        type: number
        description: Unique identifier representing a specific player.
      name:
        type: string
        description: Name of a player.